# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Waste Less
email: wasteless8@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  We are fighting local food waste by picking up food that would otherwise be thrown out.
baseurl: "/wastingless"# the subpath of your site, e.g. /blog
site.github.url: ""
url: "http://wastingless.github.io/" # the base hostname & protocol for your site
twitter_username: _wasteless_

# Build settings
markdown: kramdown

collections:
    - partners
